# Generated by Django 2.2.4 on 2019-08-11 18:36

import djUI.custom_duration
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('logo', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('duration', djUI.custom_duration.Duration()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djUI.Company')),
            ],
            options={
                'verbose_name': 'Job type',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djUI.Company')),
                ('job_type', models.ManyToManyField(to='djUI.JobType')),
            ],
            options={
                'verbose_name': 'Worker',
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('job_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djUI.JobType')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djUI.Worker')),
            ],
            options={
                'verbose_name': 'Scheduled job',
            },
        ),
    ]
