# Generated by Django 2.2.4 on 2019-08-31 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djUI', '0002_auto_20190831_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjob',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djUI.JobType'),
        ),
    ]
