# Generated by Django 2.2.4 on 2019-08-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djUI', '0004_jobtype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtype',
            name='color',
        ),
        migrations.AddField(
            model_name='jobtype',
            name='hex_color',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
